---
- name: virtualbox role
  tags:
  - virtualbox
  block:

  # present
  - when: virtualbox_apt_state == "present"
    ansible.builtin.import_tasks: ./apt_state_present.yml

  # absent
  - when: virtualbox_apt_state == "absent"
    ansible.builtin.import_tasks: ./apt_state_absent.yml
      